"""adicionar a coluna sprint de execucao da equipe

Revision ID: 53588b45571b
Revises: 
Create Date: 2025-08-03 12:46:32.786030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53588b45571b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_execucao_equipe')
    with op.batch_alter_table('execucao_equipe', schema=None) as batch_op:
        batch_op.drop_column('criado_por')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execucao_equipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_por', sa.INTEGER(), nullable=True))

    op.create_table('_alembic_tmp_execucao_equipe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('equipe_id', sa.INTEGER(), nullable=False),
    sa.Column('contexto', sa.TEXT(), nullable=True),
    sa.Column('resposta', sa.TEXT(), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), nullable=True),
    sa.Column('atualizado_em', sa.DATETIME(), nullable=True),
    sa.Column('sprint', sa.INTEGER(), nullable=True),
    sa.Column('criado_por', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['usuario.id'], name=op.f('fk_execucao_equipe_usuario')),
    sa.ForeignKeyConstraint(['equipe_id'], ['equipe_inteligente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
