"""Gerenciamento de usuários

Revision ID: b4777e6c2abd
Revises: 
Create Date: 2025-08-04 22:22:52.948544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4777e6c2abd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temporary_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_expira_em', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['temporary_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token_expira_em')
        batch_op.drop_column('temporary_token')

    # ### end Alembic commands ###
